version: '2'

services:
    db:
        container_name: container_mysql
        image: mysql
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        container_name: container_phpfpm
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${Magento2_APP_PATH}:/var/www/magento2
            - ./logs/magento2:/var/www/magento2/app/logs
        ports:
          - "9000:9000"
    web_server:
        container_name: container_magento2
        image: alexcheng/magento2
        depends_on:
          - php
          - nginx
        volumes:
          - ./magento2:/var/www/magento2
    nginx:
        container_name: container_nginx
        build:
            context: nginx
            args:
                MAX_EXECUTION_TIME: ${MAX_EXECUTION_TIME}
        ports:
            - "80:80"
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    rabbit:
        container_name: container_rabbit
        hostname: rabbit
        image: rabbitmq:3-management
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
        ports:
            - "5672:5672"
            - "15672:15672"
